# Generated by Django 3.2.7 on 2022-09-21 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visit', '0003_auto_20220920_2030'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='paitient_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
