# Generated by Django 3.2.7 on 2022-09-26 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visit', '0004_visit_paitient_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='cost',
            field=models.IntegerField(default=100),
        ),
    ]
