# Generated by Django 3.2.7 on 2022-09-28 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visit', '0006_alter_visit_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_id', models.CharField(blank=True, max_length=50, null=True)),
                ('imageUrl', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
