# Generated by Django 3.2.7 on 2022-09-21 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientaccountdetails',
            name='relationship',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
