# Generated by Django 3.2.7 on 2022-09-26 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0002_patientaccountdetails_relationship'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountdetails',
            name='imageUrl',
            field=models.CharField(blank=True, max_length=1500, null=True),
        ),
    ]
